### ISSUE TITLE
Can you provide a config for R-FCN like e2e_faster_rcnn_R-50-C4_1x.yaml?

### ISSUE THREAD

**Issue by Sundrops** [facebookresearch/Detectron#107]
Thanks for your excellent work.  @rbgirshick 
Can you provide a config for R-FCN like e2e_faster_rcnn_R-50-C4_1x.yaml
And I can't find the loss of rpn in r-fcn model.  Does it need precomputed proposals?
Here is my config for rfcn.
```yaml
MODEL:
  TYPE: rfcn
  CONV_BODY: ResNet.add_ResNet101_conv5_body
  NUM_CLASSES: 18
  # FASTER_RCNN: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.0025
  GAMMA: 0.1
  MAX_ITER: 60000
  STEPS: [0, 40000, 50000]
TRAIN:
  WEIGHTS: ./pretrain_models/R-101.pkl
  DATASETS: ('mydataset_train',)
  SCALES: (800,)
  MAX_SIZE: 1333
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  SNAPSHOT_ITERS: 10000
TEST:
  DATASETS: ('mydataset_test',)
  SCALES: (800,)
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
  FORCE_JSON_DATASET_EVAL: True
OUTPUT_DIR: ./output
```
