### ISSUE TITLE
Using non 0 GPU id in infer_simple fails

### ISSUE THREAD

**Issue by srishti-hike** [facebookresearch/Detectron#292]
I can run infer_simple.py and it works fine. If I change it to use a gpu_id to 1 instead of the default value of 0, it fails. 
Only code change in infer_simple.py
model = infer_engine.initialize_model_from_cfg()
was changed to 
model = infer_engine.initialize_model_from_cfg(1)

### Expected results
I expected it to use GPU 1 and run inference.

### Actual results

What did you observe instead?
Errors:
python2 tools/infer_simple.py     --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml     --output-dir /tmp/detectron-visualizations     --image-ext jpg     --wts https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl srishti
WARNING cnn.py:  40: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
INFO net.py:  57: Loading weights from: /tmp/detectron-download-cache/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl
terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at common_gpu.cc:144] error == cudaSuccess. 10 vs 0. Error at: /home/ubuntu/caffe2/caffe2/core/common_gpu.cc:144: invalid device ordinal
*** Aborted at 1521116584 (unix time) try "date -d @1521116584" if you are using GNU date ***
PC: @     0x7f374376f428 gsignal
*** SIGABRT (@0x3e800003e2f) received by PID 15919 (TID 0x7f3744a0e700) from PID 15919; stack trace: ***
    @     0x7f374376f4b0 (unknown)
    @     0x7f374376f428 gsignal
    @     0x7f374377102a abort
    @     0x7f373cebfb39 __gnu_cxx::__verbose_terminate_handler()
    @     0x7f373cebe1fb __cxxabiv1::__terminate()
    @     0x7f373cebd640 __cxa_call_terminate
    @     0x7f373cebde6f __gxx_personality_v0
    @     0x7f373cc24564 _Unwind_RaiseException_Phase2
    @     0x7f373cc2481d _Unwind_RaiseException
    @     0x7f373cebe409 __cxa_throw
    @     0x7f36e10e7104 caffe2::CaffeCudaSetDevice()
    @     0x7f3737de9e65 caffe2::ThreadLocalCUDAObjects::GetStream()
    @     0x7f3737dea2ee caffe2::CUDAContext::FinishDeviceComputation()
    @     0x7f3737dea581 caffe2::CUDAContext::~CUDAContext()
    @     0x7f3737decb26 caffe2::python::TensorFeeder<>::FeedTensor()
    @     0x7f3737d93f3e _ZZN8pybind1112cpp_function10initializeIZN6caffe26python16addGlobalMethodsERNS_6moduleEEUlRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_6objectESE_E38_bJSD_SE_SE_EJNS_4nameENS_5scopeENS_7siblingEA1_cNS_3argESK_NS_5arg_vEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESZ_
    @     0x7f3737dba3e3 pybind11::cpp_function::dispatcher()
    @     0x7f3744513615 PyEval_EvalFrameEx
    @     0x7f37445154e9 PyEval_EvalCodeEx
    @     0x7f3744512482 PyEval_EvalFrameEx
    @     0x7f37445154e9 PyEval_EvalCodeEx
    @     0x7f3744512482 PyEval_EvalFrameEx
    @     0x7f37445154e9 PyEval_EvalCodeEx
    @     0x7f3744512482 PyEval_EvalFrameEx
    @     0x7f37445154e9 PyEval_EvalCodeEx
    @     0x7f3744512482 PyEval_EvalFrameEx
    @     0x7f37445154e9 PyEval_EvalCodeEx
    @     0x7f374451570a PyEval_EvalCode
    @     0x7f374452e93d run_mod
    @     0x7f374452fab8 PyRun_FileExFlags
    @     0x7f3744530cd8 PyRun_SimpleFileExFlags
    @     0x7f3744542d3c Py_Main
Aborted (core dumped)

### Detailed steps to reproduce
Change in infer_simple.py
model = infer_engine.initialize_model_from_cfg(1)
Then run command
```
python2 tools/infer_simple.py     --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml     --output-dir /tmp/detectron-visualizations     --image-ext jpg     --wts https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl srishti
```

**Comment by useafterfree** [comment]
I think you need `export CUDA_VISIBLE_DEVICES=0,1,2,3,4` with a list of your available devices:
https://github.com/facebookresearch/Detectron/blob/eddb1301d95e870ed4898c15550f12c9e1fb1e58/lib/utils/subprocess.py#L57

If you want the APP to target a specific device use `export CUDA_VISIBLE_DEVICES=n` with n as the device ID you wish to target.

**Comment by ir413** [comment]
Hi @srishti-hike, as suggested by @useafterfree and noted in the [FAQ](https://github.com/facebookresearch/Detectron/blob/master/FAQ.md#q-how-do-i-restrict-detectron-to-use-only-a-subset-of-the-gpus-on-a-server) use the `CUDA_VISIBLE_DEVICES` environment variable  instead of modifying the code.

**Comment by huawei-tomas** [comment]
I'm getting the same error using `CUDA_VISIBLE_DEVICES=n` to target a specific GPU.

**Comment by huawei-tomas** [comment]
Here's how I'm calling infer_simple.
```python
import everything

gpu_id = 3
def init_caffe2():
    """Initialize caffe2 ONCE so we don't have to do it over and over.
    """
    workspace.GlobalInit(['caffe2', '--caffe2_log_level=0'])
    logger = logging.getLogger(__name__)

    weights = "https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rc$

    arg_cfg = os.path.join(os.environ['DETECTRON_HOME'],'configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml')
    output_ext = 'pdf' 

    merge_cfg_from_file(arg_cfg)
    cfg.NUM_GPUS = 1
    weights = cache_url(weights, cfg.DOWNLOAD_CACHE)
    assert_and_infer_cfg(cache_urls=False)

    assert not cfg.MODEL.RPN_ONLY, \
        'RPN models are not supported'
    assert not cfg.TEST.PRECOMPUTED_PROPOSALS, \
        'Models that require precomputed proposals are not supported'

    model = infer_engine.initialize_model_from_cfg(weights,gpu_id=gpu_id)

    return model

model = init_caffe2()

app = Flask(__name__)
api = Api(app)

class Detectron(Resource):
    """Get an input image and run FasterRCNN on it to get bboxes.
    """
    def put(self, image_id):
        img_url= request.form['data']
        r = http.request("GET", img_url)
        if r.status == 200:
            im = np.array(Image.open(io.BytesIO(r.data)).convert("RGB"))
        else:
            return jsonify([])

        with c2_utils.NamedCudaScope(gpu_id):
            cls_boxes, _, _ = infer_engine.im_detect_all(
                model, im, None
            )

        bboxes = []
        for x in cls_boxes:
            if hasattr(x, 'tolist'):
                bboxes.append(x.tolist())
            else:
                bboxes.append([])

        return jsonify(bboxes)

    def get(self, image_id):
        return jsonify(image_id)



api.add_resource(Detectron, '/<string:image_id>')

if __name__ == "__main__":
    app.run(debug=True)

```

Here's the error I'm getting.
```
INFO:detectron.utils.net:conv1_w loaded from weights file into gpu_3/conv1_w: (64, 3, 7, 7)
terminate called after throwing an instance of 'at::Error'
  what():  [enforce fail at common_gpu.cc:129] error == cudaSuccess. 10 vs 0. Error at: /home/thomas/code/pytorch/caffe2/core/common_gpu.cc:129: invalid device ordinal
*** Aborted at 1537392621 (unix time) try "date -d @1537392621" if you are using GNU date ***
PC: @     0x7fbdf6324428 gsignal
*** SIGABRT (@0x3ea00007b31) received by PID 31537 (TID 0x7fbdf6ad3700) from PID 31537; stack trace: ***
    @     0x7fbdf66ca390 (unknown)
    @     0x7fbdf6324428 gsignal
    @     0x7fbdf632602a abort
    @     0x7fbdf00b284d __gnu_cxx::__verbose_terminate_handler()
    @     0x7fbdf00b06b6 (unknown)
    @     0x7fbdf00af6a9 (unknown)
    @     0x7fbdf00b0005 __gxx_personality_v0
    @     0x7fbdefe1cf83 (unknown)
    @     0x7fbdefe1d487 _Unwind_Resume
    @     0x7fbd9d4b706b caffe2::CaffeCudaSetDevice()
    @     0x7fbdae18d205 caffe2::ThreadLocalCUDAObjects::GetStream()
    @     0x7fbdae18d5dd caffe2::CUDAContext::FinishDeviceComputation()
    @     0x7fbdae18d6b3 caffe2::CUDAContext::~CUDAContext()
    @     0x7fbdae18fa44 caffe2::python::TensorFeeder<>::FeedTensor()
    @     0x7fbdae11f4be _ZZN8pybind1112cpp_function10initializeIZN6caffe26python16addObjectMethodsERNS_6moduleEEUlPNS2_4BlobERKNS_6objectES8_E7_bJS7_SA_S8_EJNS_4nameENS_9is_methodENS_7siblingEA64_cNS_3argENS_5arg_vEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESV_
    @     0x7fbdae15af60 pybind11::cpp_function::dispatcher()
    @           0x4c37ed PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4c16e7 PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4c16e7 PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4c16e7 PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4c16e7 PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4c16e7 PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4c1e6f PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4eb30f (unknown)
    @           0x4e5422 PyRun_FileExFlags
Aborted (core dumped)
```
config file:
```yaml
MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet101_conv5_body
  NUM_CLASSES: 81
  FASTER_RCNN: True
  MASK_ON: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.02
  GAMMA: 0.1
  MAX_ITER: 180000
  STEPS: [0, 120000, 160000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
MRCNN:
  ROI_MASK_HEAD: mask_rcnn_heads.mask_rcnn_fcn_head_v1up4convs
  RESOLUTION: 28  # (output mask resolution) default 14
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14  # default 7
  ROI_XFORM_SAMPLING_RATIO: 2  # default 0
  DILATION: 1  # default 2
  CONV_INIT: MSRAFill  # default GaussianFill
TRAIN:
  WEIGHTS: https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-101.pkl
  DATASETS: ('coco_2014_train', 'coco_2014_valminusminival')
  SCALES: (800,)
  MAX_SIZE: 1333
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
TEST:
  DATASETS: ('coco_2014_minival',)
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
OUTPUT_DIR: .
```
