### ISSUE TITLE
Maybe a small bug in yaml.dump

### ISSUE THREAD

**Issue by XiongweiWu** [facebookresearch/Detectron#4]
Hi thx for your excellent work. I notice a small bug when running your code in my side. When save cfg file using yaml (https://github.com/facebookresearch/Detectron/blob/efc0c0ed9abcc48dd82d85556f31bf893ac6661c/lib/utils/subprocess.py#L48, https://github.com/facebookresearch/Detectron/blob/efc0c0ed9abcc48dd82d85556f31bf893ac6661c/lib/core/test_retinanet.py#L245) , cfg.PIXEL_MEANS should transfer its type from array to list to my understanding, otherwise, a bug reports. Maybe u can check it.

**Comment by rbgirshick** [comment]
@XiongweiWu: perhaps I don't understand the concern, but this should be fine as the type information will be embedded in the yaml.

E.g., this passes:
```
import numpy as np
import yaml

assert type(yaml.load(yaml.dump(dict(foo=np.array([1,2,3]))))['foo']) == np.ndarray
```

Also see:
```
print(yaml.dump(dict(foo=np.array([1,2,3]))))
```

Outputs:
```
foo: !!python/object/apply:numpy.core.multiarray._reconstruct
  args:
  - !!python/name:numpy.ndarray ''
  - !!python/tuple [0]
  - b
  state: !!python/tuple
  - 1
  - !!python/tuple [3]
  - !!python/object/apply:numpy.dtype
    args: [i8, 0, 1]
    state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
  - false
  - "\x01\0\0\0\0\0\0\0\x02\0\0\0\0\0\0\0\x03\0\0\0\0\0\0\0"
```
