### ISSUE TITLE
Configs proportion on single GPU

### ISSUE THREAD

**Issue by ambigus9** [facebookresearch/Detectron#530]
I has been noted there is a proportion on multiGPU configs exposed on [Getting Started](https://github.com/facebookresearch/Detectron/blob/master/configs/getting_started/tutorial_1gpu_e2e_faster_rcnn_R-50-FPN.yaml#L14), here is:

```
  # Equivalent schedules with...
  # 1 GPU:
  #   BASE_LR: 0.0025
  #   MAX_ITER: 60000
  #   STEPS: [0, 30000, 40000]
  # 2 GPUs:
  #   BASE_LR: 0.005
  #   MAX_ITER: 30000
  #   STEPS: [0, 15000, 20000]
  # 4 GPUs:
  #   BASE_LR: 0.01
  #   MAX_ITER: 15000
  #   STEPS: [0, 7500, 10000]
  # 8 GPUs:
  #   BASE_LR: 0.02
  #   MAX_ITER: 7500
  #   STEPS: [0, 3750, 5000]
```
As you can see, the factor is **BASE_LR * N_GPU** and **[ MAX_ITER , STEPS ] / N_GPU**
So, I would like to know if this factor must be preserve on all configs we will use, I mean, In all configs of [12_2017_baselines](https://github.com/facebookresearch/Detectron/tree/master/configs/12_2017_baselines) we see the base config is on 8 GPUs, so If we have less than 8 GPUs we must adjust BASE_LR, MAX_ITER and STEPS as follows:

**BASE_LR / N_GPU** and **[ MAX_ITER , STEPS ] * N_GPU**

For example,

On [e2e_mask_rcnn_R-101-FPN_1x.yaml](https://github.com/facebookresearch/Detectron/blob/master/configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_1x.yaml) we have the following config:

```
NUM_GPUS: 8
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.02
  GAMMA: 0.1
  MAX_ITER: 90000
STEPS: [0, 60000, 80000]
```

So, If I have only 1 GPU, I must to modify as follows:

```
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.0025
  GAMMA: 0.1
  MAX_ITER: 720000
STEPS: [0, 540000, 640000]
```
I'm correct, ain't I?

**Comment by ir413** [comment]
Hi @ambigus9 - as explained in the [getting started tutorial](https://github.com/facebookresearch/Detectron/blob/master/GETTING_STARTED.md#2-multi-gpu-training), if you're changing the minibatch size in any way (e.g. going from 8 GPUs to 1 GPU) we recommend that you adjust the training schedule using the [linear scaling rule](https://arxiv.org/abs/1706.02677). It seems that the modified config you posted is not consistent with the linear scaling rule (double-check the `STEPS` values; `540000 -> 480000`).

**Comment by ambigus9** [comment]
@ir413 Thanks. So, the correct values are this:

```
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.0025
  GAMMA: 0.1
  MAX_ITER: 720000
STEPS: [0, 480000, 640000]
```

If there are correct, it means that the **BASE_LR** is divided by the number of **GPUs**, right?
