### ISSUE TITLE
Retinanet cannot detect some objects in image

### ISSUE THREAD

**Issue by Acuno41** [facebookresearch/Detectron#532]
Hello everyone.

### Expected results

I use retinanet_R-101-FPN_2x to train my own dataset. I have 9 class +1 background and total 700 images. Train and test images are 4912x3684 pixels and object bounding boxes around 80x100 to 180x200 pixel. When i use ``` test_net.py ``` and ``` visualize_results.py ``` after training, i expected to detect all objects in the image. 

### Actual results

I want to detect that small objecsts in images. After visualizing results, some objects could not be detected. But their size and shape look similar to detected objects.

### Detailed steps to reproduce

The commands that i run:

```
python2 tools/train_net.py --cfg  configs/12_2017_baselines/retinanet_R-101-FPN_2x.yaml OUTPUT_DIR /media/Data/Detectron_Retnet_train12
```
```
python2 tools/test_net.py  --cfg configs/12_2017_baselines/retinanet_R-101-FPN_2x.yaml TEST.WEIGHTS /media/Data/Detectron_Retnet_train12/train/im_train/retinanet/model_iter154999.pkl NUM_GPUS 1

```
```
python2 tools/visualize_results.py --dataset im_val --detections test/im_val/retinanet/detections.pkl --thresh 0.1
```
Config files:
```
MODEL:
  TYPE: retinanet
  CONV_BODY: FPN.add_fpn_ResNet101_conv5_body
  NUM_CLASSES: 10
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.001
  GAMMA: 0.1
  MAX_ITER: 180000
  STEPS: [0, 120000, 160000]
FPN:
  FPN_ON: True
  MULTILEVEL_RPN: True
  RPN_MAX_LEVEL: 7
  RPN_MIN_LEVEL: 3
  COARSEST_STRIDE: 128
  EXTRA_CONV_LEVELS: True
  RPN_ANCHOR_START_SIZE: 12 
RETINANET:
  RETINANET_ON: True
  NUM_CONVS: 4
  ASPECT_RATIOS: (1.0, 2.0, 0.5)
  SCALES_PER_OCTAVE: 3
  ANCHOR_SCALE: 2 
  LOSS_GAMMA: 2.0
  LOSS_ALPHA: 0.25
TRAIN:
  WEIGHTS: /tmp/detectron-download-cache/ImageNetPretrained/MSRA/R-101.pkl #https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-101.pkl
  DATASETS: ('im_train',)
  SCALES: (1000,)
  IMS_PER_BATCH: 2
  BATCH_SIZE_PER_IM: 512
  MAX_SIZE: 1333
  RPN_STRADDLE_THRESH: -1  # default 0
  USE_FLIPPED: False
  SNAPSHOT_ITERS: 5000  
TEST:
  FORCE_JSON_DATASET_EVAL: True
  DATASETS: ('im_val',)
  SCALE: 1000 
  MAX_SIZE: 1333 
  RPN_PRE_NMS_TOP_N: 10000  # Per FPN level
  RPN_POST_NMS_TOP_N: 8000
  NMS: 0.1 
  DETECTIONS_PER_IM: 3000 
  RPN_NMS_THRESH: 0.7

OUTPUT_DIR: .
```

### System information

* Operating system: Ubuntu 16.04
* Compiler version: gcc 5.4.0
* CUDA version: 8.0
* cuDNN version: 7.0.5
* NVIDIA driver version: 384.111
* GPU models (for all devices if they are not all the same): 1 TITAN Xp
