### ISSUE TITLE
how to set the anchor scales in RetinaNet?

### ISSUE THREAD

**Issue by lilichu** [facebookresearch/Detectron#541]
hi!
in yaml file:
```
RETINANET:
  RETINANET_ON: True
  NUM_CONVS: 4
  ASPECT_RATIOS: (1.0, 2.0, 0.5)
  SCALES_PER_OCTAVE: 3
  ANCHOR_SCALE: 4
```

there are `ASPECT_RATIOS`, `SCALES_PER_OCTAVE`, `ANCHOR_SCALE`.  but how to set three kinds of anchor  scales?  In the focal loss paper the scales are 4 * [2^0, 2^(1/3), 2^(2/3)].
