### ISSUE TITLE
Error finding ResNet weights during training

### ISSUE THREAD

**Issue by JosephPB** [facebookresearch/Detectron#721]
When trying to train the network on my own dataset the following error was flagged:

```
loading annotations into memory...
Done (t=0.31s)
creating index...
index created!
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-35-49e97be6d079> in <module>()
----> 1 checkpoints = detectron.utils.train.train_model()

/efs/data/jpb/api/Detectron/detectron/utils/train.py in train_model()
     56         return checkpoints
     57 
---> 58     setup_model_for_training(model, weights_file, output_dir)
     59     training_stats = TrainingStats(model)
     60     CHECKPOINT_PERIOD = int(cfg.TRAIN.SNAPSHOT_ITERS / cfg.NUM_GPUS)

/efs/data/jpb/api/Detectron/detectron/utils/train.py in setup_model_for_training(model, weights_file, output_dir)
    159     if weights_file:
    160         # Override random weight initialization with weights from a saved model
--> 161         nu.initialize_gpu_from_weights_file(model, weights_file, gpu_id=0)
    162     # Even if we're randomly initializing we still need to synchronize
    163     # parameters across GPUs

/efs/data/jpb/api/Detectron/detectron/utils/net.py in initialize_gpu_from_weights_file(model, weights_file, gpu_id)
     59     logger.info('Loading weights from: {}'.format(weights_file))
     60     ws_blobs = workspace.Blobs()
---> 61     with open(weights_file, 'rb') as f:
     62         try:
     63             src_blobs = pickle.load(f, encoding='latin1')  # the pickles from the Model Zoo (as of January 2018) seem to be encoded with latin1; see also https://github.com/tflearn/tflearn/issues/57

FileNotFoundError: [Errno 2] No such file or directory: 'https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-101.pkl'
```

### Detailed steps to reproduce

I created a COCO annotations `juba_test` file which specified the locations of the images to train and gave their annotations. This file has the following format (this is a small example):

```
{"info": 
{"contributor": "", "date_created": "2018/06/20", "description": "test", "url": "", "version": "1.0", "year": 2018}, 
"licenses": [{"id": 1, "name": "", "url": ""}], 
"categories": [{"id": 1, "name": "structure", "supercategory": "structure"}], 
"images": 
    [{"coco_url": "", "date_captured": "", "file_name": "doro-x3000y300.png", "flickr_url": "", "height": 300, "id": 1, "license": 1, "width": 300}, 
    {"coco_url": "", "date_captured": "", "file_name": "doro-x6000y1200.png", "flickr_url": "", "height": 300, "id": 2, "license": 1, "width": 300}], 
"annotations": 
    [{"id": 1, "image_id": 1, "area": 120, "bbox": [254, 228, 10, 12], "category_id": 1, "iscrowd": 0, "segmentation": []}, 
    {"id": 1, "image_id": 1, "area": 90, "bbox": [283, 218, 9, 10], "category_id": 1, "iscrowd": 0, "segmentation": []}, 
    {"id": 1, "image_id": 2, "area": 70, "bbox": [2, 8, 7, 10], "category_id": 1, "iscrowd": 0, "segmentation": []}, 
    {"id": 1, "image_id": 2, "area": 56, "bbox": [288, 107, 7, 8], "category_id": 1, "iscrowd": 0, "segmentation": []}, 
    {"id": 1, "image_id": 2, "area": 56, "bbox": [290, 152, 7, 8], "category_id": 1, "iscrowd": 0, "segmentation": []}]}
```
Then ran:

```
config_file = 'config/test.yaml'
num_training_iterations = len(file_ids.keys())*10
merge_cfg_from_file(config_file)
merge_cfg_from_list(['TRAIN.DATASETS',('juba_test,),
                     'SOLVER.MAX_ITER',num_training_iterations])

assert_and_infer_cfg(cache_urls=False, make_immutable=False)
workspace.GlobalInit(
    ['caffe2', '--caffe2_log_level=0', '--caffe2_gpu_memory_tracking=1']
)
checkpoints = detectron.utils.train.train_model()
```
which flagged the error.

My config file looks like this:

```
MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet101_conv5_body
  NUM_CLASSES: 2
  FASTER_RCNN: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.005
  GAMMA: 0.1
  MAX_ITER: 5000
  STEPS: [0, 120000, 160000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
  RPN_ANCHOR_START_SIZE: 16
  RPN_ASPECT_RATIOS: (1,)
  RPN_MAX_LEVEL: 5
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  WEIGHTS: https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-101.pkl
  DATASETS: ('juba_test',)
  SCALES: (300,)
  MAX_SIZE: 300
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  SNAPSHOT_ITERS: 1000
  IMS_PER_BATCH: 4
  AUTO_RESUME: False
TEST:
  DATASETS: ()
  SCALE: 300
  MAX_SIZE: 300
  FORCE_JSON_DATASET_EVAL: True
  NMS: 0.3
  DETECTIONS_PER_IM: 2000
  SCORE_THRESH: 0.05
  SOFT_NMS:
      ENABLED: True
  
OUTPUT_DIR: unosat/models/
```

### System information

* Conda 3
* Python 3
* CUDA 9 [ sudo dpkg -i cuda-repo-ubuntu1604-9-0-local_9.0.176-1_amd64.deb + sudo apt-key add /var/cuda-repo-9-0-local/7fa2af80.pub + sudo apt-get update + sudo apt-get install cuda ]
* CuDNN 7.1 [ sudo dpkg -i libcudnn7_7.1.4.18-1+cuda9.0_amd64.deb + sudo dpkg -i libcudnn7-dev_7.1.4.18-1+cuda9.0_amd64.deb + sudo dpkg -i libcudnn7-doc_7.1.4.18-1+cuda9.0_amd64.deb ]
* NCCL 2.2 [ sudo dpkg -i nvidia-machine-learning-repo-ubuntu1604_1.0.0-1_amd64 + sudo apt install libnccl2=2.2.13-1+cuda9.0 libnccl-dev=2.2.13-1+cuda9.0] 
* Caffe2 for CUDA9/CuDNN7 [ conda install -c caffe2 caffe2-cuda9.0-cudnn7=0.8.dev=py36_2018.05.14 (NOTE: more recent build may break the setup) ]
* AWS GPU instance

### Update

If I download the ResNet weights then it appears to train, but we can't it grab them from the url?

Additionally, when running `checkpoints = detectron.utils.train.train_model()` is that retraining just the head nodes of the ResNet backbone, and then training the segmentation, classification and box regression networks from scratch? If so, is there a setting on the Detectron, like on the original implementation of MaskRCNN where you can decide if you want to retrain all the weights in the backbone structure or just the head nodes?

Thanks for the help!
