### ISSUE TITLE
PROPOSAL_FILES error when evaluating

### ISSUE THREAD

**Issue by JosephPB** [facebookresearch/Detectron#735]
### Expected results

I'm trying to run `run_inference` on a dataset to eventually extract the precision and recall.

### Actual results

I get the following error:

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-10-d1ed3834cb68> in <module>()
      2     #cfg.TEST.DATASETS,
      3     weights_file = cfg.TEST.WEIGHTS,
----> 4     check_expected_results=True,
      5     #gpu_id = 0,
      6 )

/efs/data/jpb/Detectron/Detectron/detectron/core/test_engine.py in run_inference(weights_file, ind_range, multi_gpu_testing, gpu_id, check_expected_results)
    126             )
    127 
--> 128     all_results = result_getter()
    129     if check_expected_results and is_parent:
    130         task_evaluation.check_expected_results(

/efs/data/jpb/Detectron/Detectron/detectron/core/test_engine.py in result_getter()
     99             all_results = {}
    100             for i in range(len(cfg.TEST.DATASETS)):
--> 101                 dataset_name, proposal_file = get_inference_dataset(i)
    102                 output_dir = get_output_dir(dataset_name, training=False)
    103                 results = parent_func(

/efs/data/jpb/Detectron/Detectron/detectron/core/test_engine.py in get_inference_dataset(index, is_parent)
     74             'The child inference process can only work on a single proposal file'
     75         assert len(cfg.TEST.PROPOSAL_FILES) == len(cfg.TEST.DATASETS), \
---> 76             'If proposals are used, one proposal file must be specified for ' \
     77             'each dataset'
     78         proposal_file = cfg.TEST.PROPOSAL_FILES[index]

AssertionError: If proposals are used, one proposal file must be specified for each dataset
```

### Detailed steps to reproduce

I pass the config file:

```
MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet101_conv5_body
  NUM_CLASSES: 2
  FASTER_RCNN: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.005
  GAMMA: 0.1
  MAX_ITER: 5000
  STEPS: [0, 120000, 160000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
  RPN_ANCHOR_START_SIZE: 16
  RPN_ASPECT_RATIOS: (1,)
  RPN_MAX_LEVEL: 5
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  WEIGHTS: https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-101.pkl
  DATASETS: ('unosat_doro_basenet_train', 'unosat_doro_basenet_val')
  SCALES: (300,)
  MAX_SIZE: 300
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  SNAPSHOT_ITERS: 1000
  IMS_PER_BATCH: 4
  AUTO_RESUME: False
TEST:
  DATASETS: ()
  SCALE: 300
  MAX_SIZE: 300
  FORCE_JSON_DATASET_EVAL: True
  NMS: 0.3
  DETECTIONS_PER_IM: 2000
  SCORE_THRESH: 0.05
  SOFT_NMS:
      ENABLED: True
  
OUTPUT_DIR: .
```

Then the test weights:
```
weights = './models/detectron/train/unosat_doro_basenet_train:unosat_doro_basenet_val/generalized_rcnn/model_final.pkl'
```
```
workspace.GlobalInit(
    ['caffe2', '--caffe2_log_level=0']
)
```

```
merge_cfg_from_file(config_file)
merge_cfg_from_list(['TEST.DATASETS',('doro_tiny_adaptation_demo',),
                     #'MODEL.MASK_ON', False,
                     #'TEST.PROPOSAL_FILES',('ajuong_basenet_test',),
                     'TEST.WEIGHTS',weights])
```
```
results = run_inference(
    weights_file = cfg.TEST.WEIGHTS,
    check_expected_results=True,
)
```

This flags the error.

### System information

* Conda 3
* Python 3
* CUDA 9 [ sudo dpkg -i cuda-repo-ubuntu1604-9-0-local_9.0.176-1_amd64.deb + sudo apt-key add /var/cuda-repo-9-0-local/7fa2af80.pub + sudo apt-get update + sudo apt-get install cuda ]
* CuDNN 7.1 [ sudo dpkg -i libcudnn7_7.1.4.18-1+cuda9.0_amd64.deb + sudo dpkg -i libcudnn7-dev_7.1.4.18-1+cuda9.0_amd64.deb + sudo dpkg -i libcudnn7-doc_7.1.4.18-1+cuda9.0_amd64.deb ]
* NCCL 2.2 [ sudo dpkg -i nvidia-machine-learning-repo-ubuntu1604_1.0.0-1_amd64 + sudo apt install libnccl2=2.2.13-1+cuda9.0 libnccl-dev=2.2.13-1+cuda9.0]
* Caffe2 for CUDA9/CuDNN7 [ conda install -c caffe2 caffe2-cuda9.0-cudnn7=0.8.dev=py36_2018.05.14 (NOTE: more recent build may break the setup) ]
* AWS GPU instance
