### ISSUE TITLE
Train_net.py Crashes for simple R-FCN + Resnet-50 setup -> Runtime Error [ enforce fail at operator.cc:46]

### ISSUE THREAD

**Issue by sairams-intel** [facebookresearch/Detectron#770]
- I'm looking to train R-FCN with a Resnet-101 backbone. 
- To start with, I wanted to make sure my setup was correct, so I used `tutorial_1gpu_e2e_faster_rcnn_R-50-FPN.yaml` to train Faster R-CNN with `coco-2014` and this trained and evaluated on the dataset without any issues
- I then modified the yaml file to train R-FCN with Resnet-50 and all other parameters remaining the same. I get a crash when I run the `train_net.py' script. 
- I have searched this repo's issues for possible fixes but haven't found any. 

Can someone please help?

### Expected results

Model training successfully and evaluating on coco-minival-2014

### Actual results

Here is the stack trace:
```
Traceback (most recent call last):
  File "tools/train_net.py", line 132, in <module>
    main()
  File "tools/train_net.py", line 114, in main
    checkpoints = detectron.utils.train.train_model()
  File "/localdisk/sairamsu/detectron/detectron/utils/train.py", line 58, in train_model
    setup_model_for_training(model, weights_file, output_dir)
  File "/localdisk/sairamsu/detectron/detectron/utils/train.py", line 178, in setup_model_for_training
    workspace.CreateNet(model.net)
  File "/nfs/site/home/sairamsu/anaconda3/envs/sairamsu-caffe2/lib/python2.7/site-packages/caffe2/python/workspace.py", line 171, in CreateNet
    StringifyProto(net), overwrite,
  File "/nfs/site/home/sairamsu/anaconda3/envs/sairamsu-caffe2/lib/python2.7/site-packages/caffe2/python/workspace.py", line 197, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at operator.cc:46] blob != nullptr. op PSRoIPool: Encountered a non-existing input blob: gpu_0/rois
frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x59 (0x7fe0e9c68f19 in /nfs/site/home/sairamsu/anaconda3/envs/sairamsu-caffe2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libc10.so)
frame #1: caffe2::OperatorBase::OperatorBase(caffe2::OperatorDef const&, caffe2::Workspace*) + 0x4ec (0x7fe118a17d0c in /nfs/site/home/sairamsu/anaconda3/envs/sairamsu-caffe2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #2: <unknown function> + 0x6741c (0x7fe03776141c in /nfs/site/home/sairamsu/anaconda3/envs/sairamsu-caffe2/lib/python2.7/site-packages/torch/lib/libcaffe2_detectron_ops_gpu.so)
frame #3: <unknown function> + 0x6797e (0x7fe03776197e in /nfs/site/home/sairamsu/anaconda3/envs/sairamsu-caffe2/lib/python2.7/site-packages/torch/lib/libcaffe2_detectron_ops_gpu.so)
frame #4: std::_Function_handler<std::unique_ptr<caffe2::OperatorBase, std::default_delete<caffe2::OperatorBase> > (caffe2::OperatorDef const&, caffe2::Workspace*), std::unique_ptr<caffe2::OperatorBase, std::default_delete<caffe2::OperatorBase> > (*)(caffe2::OperatorDef const&, caffe2::Workspace*)>::_M_invoke(std::_Any_data const&, caffe2::OperatorDef const&, caffe2::Workspace*) + 0xf (0x7fe119e4ad0f in /nfs/site/home/sairamsu/anaconda3/envs/sairamsu-caffe2/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state_gpu.so)
frame #5: <unknown function> + 0x11a3eb7 (0x7fe118a15eb7 in /nfs/site/home/sairamsu/anaconda3/envs/sairamsu-caffe2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #6: <unknown function> + 0x11a64de (0x7fe118a184de in /nfs/site/home/sairamsu/anaconda3/envs/sairamsu-caffe2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #7: caffe2::CreateOperator(caffe2::OperatorDef const&, caffe2::Workspace*, int) + 0x340 (0x7fe118a18a90 in /nfs/site/home/sairamsu/anaconda3/envs/sairamsu-caffe2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #8: caffe2::dag_utils::prepareOperatorNodes(std::shared_ptr<caffe2::NetDef const> const&, caffe2::Workspace*) + 0x14fc (0x7fe118a05c2c in /nfs/site/home/sairamsu/anaconda3/envs/sairamsu-caffe2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #9: caffe2::AsyncNetBase::AsyncNetBase(std::shared_ptr<caffe2::NetDef const> const&, caffe2::Workspace*) + 0x287 (0x7fe1189f0c47 in /nfs/site/home/sairamsu/anaconda3/envs/sairamsu-caffe2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #10: caffe2::AsyncSchedulingNet::AsyncSchedulingNet(std::shared_ptr<caffe2::NetDef const> const&, caffe2::Workspace*) + 0x9 (0x7fe1189f64e9 in /nfs/site/home/sairamsu/anaconda3/envs/sairamsu-caffe2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #11: <unknown function> + 0x1185cae (0x7fe1189f7cae in /nfs/site/home/sairamsu/anaconda3/envs/sairamsu-caffe2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #12: <unknown function> + 0x1185b5f (0x7fe1189f7b5f in /nfs/site/home/sairamsu/anaconda3/envs/sairamsu-caffe2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #13: caffe2::CreateNet(std::shared_ptr<caffe2::NetDef const> const&, caffe2::Workspace*) + 0x6b0 (0x7fe1189e9f00 in /nfs/site/home/sairamsu/anaconda3/envs/sairamsu-caffe2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #14: caffe2::Workspace::CreateNet(std::shared_ptr<caffe2::NetDef const> const&, bool) + 0x102 (0x7fe118a44f92 in /nfs/site/home/sairamsu/anaconda3/envs/sairamsu-caffe2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #15: caffe2::Workspace::CreateNet(caffe2::NetDef const&, bool) + 0x8e (0x7fe118a4551e in /nfs/site/home/sairamsu/anaconda3/envs/sairamsu-caffe2/lib/python2.7/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #16: <unknown function> + 0x538d5 (0x7fe119e428d5 in /nfs/site/home/sairamsu/anaconda3/envs/sairamsu-caffe2/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state_gpu.so)
frame #17: <unknown function> + 0x8b258 (0x7fe119e7a258 in /nfs/site/home/sairamsu/anaconda3/envs/sairamsu-caffe2/lib/python2.7/site-packages/caffe2/python/caffe2_pybind11_state_gpu.so)
<omitting python frames>
frame #35: __libc_start_main + 0xf0 (0x7fe12ebbf830 in /lib/x86_64-linux-gnu/libc.so.6)
```
### Detailed steps to reproduce

I wrote the `tutorial_1gpu_e2e_rfcn_R-50-FPN.yaml` file as below:

```
MODEL:
  TYPE: ResNet50_rfcn
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 81
  FASTER_RCNN: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.0025
  GAMMA: 0.1
  MAX_ITER: 60000
  STEPS: [0, 30000, 40000]

FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True

RESNETS:
  RES5_DILATION: 2

RFCN:
  #RFCN_ON: True
  PS_GRID_SIZE: 7

TRAIN:
  WEIGHTS: https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
  DATASETS: ('coco_2014_train',)
  SCALES: (500,)
  MAX_SIZE: 833
  IMS_PER_BATCH: 2
  BATCH_SIZE_PER_IM: 256
  RPN_PRE_NMS_TOP_N: 2000
  SNAPSHOT_ITERS: 10000

TEST:
  DATASETS: ('coco_2014_minival',)
  SCALE: 500
  MAX_SIZE: 833
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000
  RPN_POST_NMS_TOP_N: 1000
OUTPUT_DIR: .
```
Then I ran the following command to train:
```
python tools/train_net.py --cfg configs/getting_started/tutorial_1gpu_e2e_rfcn_R-50-FPN.yaml OUTPUT_DIR /tmp/detectron-output-rfcn
```
### System information

* Operating system: Ubuntu 16.04
* Compiler version: gcc 5.4
* CUDA version: 9.0
* cuDNN version: 7.0.3
* NVIDIA driver version: 384.130
* GPU models (for all devices if they are not all the same): TITANXP
* `PYTHONPATH` environment variable: `/nfs/site/home/sairamsu/tf_training/models:/nfs/site/home/sairamsu/:/nfs/site/home/sairamsu/tf_training/models:/nfs/site/home/sairamsu/`
* `python --version` output: 2.7.15
* Anything else that seems relevant: I used pre-built Caffe2 binaries during the installation.
