### ISSUE TITLE
Unable to reproduce the results of baseline on conv5 in FPN paper

### ISSUE THREAD

**Issue by krumo** [facebookresearch/Detectron#787]
### Expected results

I'm trying to reproduce the results of baseline on conv5 in FPN paper on Cityscapes dataset. In FPN paper, using ResNet conv5 as body for RPN and Fast RCNN and 2fc as head for Fast RCNN will yield an acceptable result, though it may be worse than the results with baseline on conv4. I'm trying to reproduce this results with Cityscapes dataset.

### Actual results
However, after training over 10 epoches on the Cityscapes validation set, I got 1% mAP50 on the same validation set, which is quite different from the phenomena described in FPN paper. I wonder whether there's something wrong with my setting.

### Detailed steps to reproduce

1. create a config file named `tutorial_1gpu_e2e_faster_rcnn_R-50-C5-cityscapes.yaml` with the following content
```
MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: ResNet.add_ResNet50_conv5_body
  NUM_CLASSES: 9
  FASTER_RCNN: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0005
  LR_POLICY: steps_with_decay
  BASE_LR: 0.001
  GAMMA: 0.1
  MAX_ITER: 7000
  WARM_UP_ITERS: 0
  STEPS: [0, 5000]
RPN:
  SIZES: (32, 64, 128, 256, 512)
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  WEIGHTS: https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
  DATASETS: ('cityscapes_fine_instanceonly_seg_val',)
  SCALES: (600,)
  MAX_SIZE: 1200
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 256
TEST:
  DATASETS: ('cityscapes_fine_instanceonly_seg_val',)
  SCALE: 600
  MAX_SIZE: 1200
  RPN_PRE_NMS_TOP_N: 6000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
  FORCE_JSON_DATASET_EVAL: True
OUTPUT_DIR: .
```
2. Run the command 
`python2 tools/train_net.py --cfg configs/tutorial_1gpu_e2e_faster_rcnn_R-50-C5-cityscapes.yaml`
### System information

* Operating system: Ubuntu 16.04
* Compiler version: GCC 5.4
* CUDA version: 9.0
* cuDNN version: 7.4.2
* NVIDIA driver version: 384.130
* GPU models (for all devices if they are not all the same): Titan Xp
* `PYTHONPATH` environment variable: 
* `python --version` output: 2.7.15
