### ISSUE TITLE
Why IMS_PER_BATCH is set as 1 for e2e_faster_rcnn_R-50-C4_1x job?

### ISSUE THREAD

**Issue by huangh12** [facebookresearch/Detectron#824]
In my opinion, the GPU memory should be enough for R-50-C4_1x training with IMS_PER_BATCH=2, which is also the default batch size setting in Faster R-CNN paper. So, it's unclear why the IMS_PER_BATCH is set as 1 as below:
```
TRAIN:
  WEIGHTS: https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
  DATASETS: ('coco_2014_train', 'coco_2014_valminusminival')
  SCALES: (800,)
  MAX_SIZE: 1333
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
```
(from config/12_2017_baselines/ e2e_faster_rcnn_R-50-C4_1x.yaml)
